### ISSUE TITLE
alter regex to match fas icons as well

### ISSUE THREAD

**Issue by zber** [ffhs/moodle-filter_fontawesome#7]
there are three types of free icons: regular, brands, solid
they are called using fa, fab and fas
could you please alter the $search pattern to match "fas" as well?
could be like: $search =  "(\[((?:icon\s)?)((?:fa[bs])\s?)(fa-[a-z0-9 -]+)\])is";

e.g. [icon fas fa-user-clock] or [icon fas fa-2x fa-user-clock]
https://fontawesome.com/icons/user-clock?style=solid

in the pro version, there is also: light (fal) and duotone (fad)
e.g. [icon fad fa-abacus]
https://fontawesome.com/icons/abacus?style=duotone

I don't know the business plan of FontAwesome but to be on the safe side, probably the regex should include also future possibilities
could be like: $search =  "(\[((?:icon\s)?)((?:fa[a-z]?)\s?)(fa-[a-z0-9 -]+)\])is";

**Comment by adpe** [comment]
Thank you @zber for this issue

As they evolve FontAwesome further and further it would be better to support different types in the future. We will allow the whole alphabet (lowercase), as you suggested, in the regex.

We're working to release a new version of the plugin within the next hours.

Greets,
Adrian
